# Generated by Django 3.2.7 on 2021-10-01 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='id',
            new_name='barcode',
        ),
        migrations.RenameField(
            model_name='medicinequantity',
            old_name='id',
            new_name='order_item',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='id',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='description',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='PatientNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
