# Generated by Django 3.2.7 on 2021-10-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211001_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinequantity',
            name='medicine_id',
        ),
        migrations.RemoveField(
            model_name='medicinequantity',
            name='prescription_id',
        ),
        migrations.RemoveField(
            model_name='patientnotes',
            name='email',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pharmacist_id',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='MedicineQuantity',
        ),
        migrations.DeleteModel(
            name='PatientNotes',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
