# Generated by Django 3.2.7 on 2021-10-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_phone_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_num',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default='patient', max_length=20),
        ),
    ]
